// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTrafficChange();
void onUltrasonicChange();

CloudLight traffic;
CloudLength ultrasonic;
bool vehicleDetected;

void initProperties(){

  ArduinoCloud.addProperty(traffic, READWRITE, ON_CHANGE, onTrafficChange);
  ArduinoCloud.addProperty(ultrasonic, READWRITE, ON_CHANGE, onUltrasonicChange);
  ArduinoCloud.addProperty(vehicleDetected, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
